yum install -y \
    wget \
    git \
    cmake \
    gcc-c++ \
    gcc binutils \
    libX11-devel \
    libXpm-devel \
    libXft-devel \
    libXext-devel \
    gcc-gfortran \
    openssl-devel \
    pcre-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    glew-devel \
    ftgl-devel \
    mysql-devel \
    fftw-devel \
    cfitsio-devel \
    graphviz-devel \
    avahi-compat-libdns_sd-devel \
    libldap-dev python-devel \
    libxml2-devel \
    gsl-static \
    which \
    make \
    cvs \
    imake \
    autoconf \
    automake \
    libXt-devel \
    lesstif-devel \
    gmp-devel \
    gcc-gfortran \
    openssl-devel \
    pcre-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    glew-devel \
    ftgl-devel \
    mysql-devel \
    fftw-devel \
    cfitsio-devel \
    graphviz-devel \
    avahi-compat-libdns_sd-devel \
    libldap-dev \
    python-devel \
    libxml2-devel \
    libtool \
    gsl-static \
    svn
